[project]
name = "kogniterm"
version = "0.1.0"
description = "Un asistente de IA experto en terminal."
authors = [
    { name = "Gato Villano", email = "gato@example.com" } # Puedes cambiar esto
]
dependencies = [
    "python-dotenv",
    "langchain",
    "langchain-core",
    "langgraph",
    "prompt_toolkit",
    "langchain_mcp_adapters",
    "langchain_community",
    "bs4",
    "PyGithub",
    "rich",
    "matplotlib",
    "google-genai",
    "jupyter_client",
    "loguru",
    "colorama",
    "gitignore-parser",
    "watchdog",
    "litellm",
    "playwright",
    "GitPython",
    "pydantic",
    "pydantic-settings",
    "chromadb",
    "urllib3<2", # AÃ±adido si lo usas para la UI
    "radon",
    "pylint",
    "pyautogui",
    "pywinctl",
]
readme = "README.md"
requires-python = ">=3.9"

[project.scripts]
kogniterm = "kogniterm.terminal.terminal:main"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["kogniterm*"]
